import streamlit as st
st.title("streamlit basics")
st.header("this is header")
st.subheader("this is sub header")
st.text("im building a manufacturing process automation")
st.markdown("### this is markdown")
st.success("this is a success message")
st.info("this is an info message")
st.warning("this is a warning message")
st.error("this is an error message")
exp = ZeroDivisionError("Trying to divide by Zero")
st.exception(exp)
st.write("this is a write message")